"""Inicial Supabase

Revision ID: 44564c7a427e
Revises: 
Create Date: 2025-09-08 01:20:20.225351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44564c7a427e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('analisis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('imagen_original', sa.LargeBinary(), nullable=False),
    sa.Column('imagen_analizada', sa.LargeBinary(), nullable=True),
    sa.Column('fecha_analisis', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ubicacion_escena', sa.String(length=200), nullable=True),
    sa.Column('caso_asociado', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analisis_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('point_x', sa.Integer(), nullable=False),
    sa.Column('point_y', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.Text(), nullable=True),
    sa.Column('naturaleza', sa.Text(), nullable=True),
    sa.Column('condicion', sa.Text(), nullable=True),
    sa.Column('indicios', sa.Text(), nullable=True),
    sa.Column('pertinencia', sa.Text(), nullable=True),
    sa.Column('valor_probatorio', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('verificada', sa.Boolean(), nullable=True),
    sa.Column('fecha_verificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidencias')
    op.drop_table('analisis')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
