"""Agregar tiempos por evidencia2

Revision ID: ae6758e6696c
Revises: e1f32158da15
Create Date: 2025-10-19 13:44:52.346717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6758e6696c'
down_revision = 'e1f32158da15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiempo_inicio', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tiempo_fin', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('duracion_segundos', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidencias', schema=None) as batch_op:
        batch_op.drop_column('duracion_segundos')
        batch_op.drop_column('tiempo_fin')
        batch_op.drop_column('tiempo_inicio')

    # ### end Alembic commands ###
