"""Agregar tiempos por evidencia3

Revision ID: b805c8ac5d26
Revises: ae6758e6696c
Create Date: 2025-10-19 14:20:50.011930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b805c8ac5d26'
down_revision = 'ae6758e6696c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidencias', schema=None) as batch_op:
        batch_op.alter_column('duracion_segundos',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidencias', schema=None) as batch_op:
        batch_op.alter_column('duracion_segundos',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
