"""Add metrics fields to Analisis and Evidencia

Revision ID: f62b3d76f81a
Revises: 44564c7a427e
Create Date: 2025-09-24 21:34:00.265061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62b3d76f81a'
down_revision = '44564c7a427e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiempo_total', sa.Interval(), nullable=True))
        batch_op.add_column(sa.Column('numero_evidencias', sa.Integer(), nullable=True))

    with op.batch_alter_table('evidencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_identificacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_documentacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('es_clave', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('omitida', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('usuario_verificador_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_evidencias_es_clave'), ['es_clave'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidencias_omitida'), ['omitida'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidencias_usuario_verificador_id'), ['usuario_verificador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidencias_verificada'), ['verificada'], unique=False)
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_verificador_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidencias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_evidencias_verificada'))
        batch_op.drop_index(batch_op.f('ix_evidencias_usuario_verificador_id'))
        batch_op.drop_index(batch_op.f('ix_evidencias_omitida'))
        batch_op.drop_index(batch_op.f('ix_evidencias_es_clave'))
        batch_op.drop_column('usuario_verificador_id')
        batch_op.drop_column('omitida')
        batch_op.drop_column('es_clave')
        batch_op.drop_column('fecha_documentacion')
        batch_op.drop_column('fecha_identificacion')

    with op.batch_alter_table('analisis', schema=None) as batch_op:
        batch_op.drop_column('numero_evidencias')
        batch_op.drop_column('tiempo_total')

    # ### end Alembic commands ###
